
default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: movie_ticket_development

# test:
#   <<: *default
#   database: movie_ticket_test
#
# production:
#   <<: *default
#   database: movie_ticket_production
